<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="HangfireJobs\**" />
	  <EmbeddedResource Remove="HangfireJobs\**" />
	  <None Remove="HangfireJobs\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CloudinaryDotNet" Version="1.27.5" />
		<PackageReference Include="FirebaseAdmin" Version="3.4.0" />
		<PackageReference Include="Google.Apis.Auth" Version="1.71.0" />
		<PackageReference Include="MailKit" Version="4.17.0" />
		<PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="8.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0" />
		<PackageReference Include="Stripe.net" Version="48.2.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Tourism.Application\Tourism.Application.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Services\" />
	</ItemGroup>

</Project>


